version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@textlint-ja/textlint-rule-no-insert-dropping-sa"
    versions:
    - 1.0.2
  - dependency-name: textlint
    versions:
    - 11.8.1
    - 11.8.2
  - dependency-name: textlint-rule-preset-ja-technical-writing
    versions:
    - 4.0.1
